src/Benski/ReservationBundle/Entity/ReservationSejour.php
<?php

namespace Benski\ReservationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Benski\ReservationBundle\Entity\SejourReserve;
use Benski\ReservationBundle\Entity\ReservationImpl;

/**
 * ReservationSejour
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Benski\ReservationBundle\Entity\ReservationSejourRepository")
 * @ORM\HasLifecycleCallbacks
 */
class ReservationSejour extends ReservationImpl {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var SejourReserve
     *
     * @ORM\OneToOne(
     *      targetEntity="Benski\ReservationBundle\Entity\SejourReserve",
     *      inversedBy="reservation",
     *      cascade={"all", "remove"},
     *      orphanRemoval=true,
     *      fetch="EAGER"
     *  )
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    protected $sejourReserve;
    
    public function getNombresPersonnes(){
        return $this->getSejourReserve()->getNombresPersonnes();
    }
    
    public function equals($object) {
        if ($object == null)
            return false;
        if (!$object instanceof ReservationSejour)
            return false;
        if ($object == $this)
            return true;
        if ($this->getId() == null)
            return false;
        if ($this->getId() != $object->getId())
            return false;
        return true;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist() {
        $this->total = $this->sejourReserve->getTotal();
    }
    
    
    public function getDateDebut(){
        return $this->getSejourReserve()->getDateDebut();
    }
    
    public function getDateFin(){
        return $this->getSejourReserve()->getDateFin();
    }

    public function addSejourReserve(SejourReserve $sr) {
        $this->getSejourReserve()
                ->addAppartementsReserve($sr->getAppartementsReserves()[0]);
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return parent::getId();
    }

    /**
     * Set sejourReserve
     *
     * @param \Benski\ReservationBundle\Entity\SejourReserve $sejourReserve
     * @return ReservationSejour
     */
    public function setSejourReserve(SejourReserve $sejourReserve = null) {
        if($sejourReserve->equals($this->getSejourReserve())) return;
        $this->sejourReserve = $sejourReserve;
        $sejourReserve->setReservation($this);

        return $this;
    }

    /**
     * Get sejourReserve
     *
     * @return \Benski\ReservationBundle\Entity\SejourReserve 
     */
    public function getSejourReserve() {
        return $this->sejourReserve;
    }

}

src/Benski/ReservationBundle/Form/ReservationSejourType.php
<?php

namespace Benski\ReservationBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ReservationSejourType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('responsable')
            ->add('total')
            ->add('statut')
            ->add('dateCreation')
            ->add('dateModification')
            ->add('reductions')
            ->add('paiements')
            ->add('sejourReserve')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Benski\ReservationBundle\Entity\ReservationSejour'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'benski_reservationbundle_reservationsejour';
    }
}

src/Benski/ReservationBundle/Controller/ReservationSejourController.php
<?php

namespace Benski\ReservationBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Benski\ReservationBundle\Entity\ReservationSejour;
use Benski\ReservationBundle\Form\ReservationSejourType;

/**
 * ReservationSejour controller.
 *
 * @Route("/admin/reservation-sejour")
 */
class ReservationSejourController extends Controller
{

    /**
     * Lists all ReservationSejour entities.
     *
     * @Route("/", name="admin_reservation-sejour")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('BenskiReservationBundle:ReservationSejour')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new ReservationSejour entity.
     *
     * @Route("/", name="admin_reservation-sejour_create")
     * @Method("POST")
     * @Template("BenskiReservationBundle:ReservationSejour:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new ReservationSejour();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('admin_reservation_sejour', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
    * Creates a form to create a ReservationSejour entity.
    *
    * @param ReservationSejour $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createCreateForm(ReservationSejour $entity)
    {
        $form = $this->createForm(new ReservationSejourType(), $entity, array(
            'action' => $this->generateUrl('admin_reservation-sejour_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new ReservationSejour entity.
     *
     * @Route("/new", name="admin_reservation-sejour_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new ReservationSejour();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a ReservationSejour entity.
     *
     * @Route("/{id}", name="admin_reservation_sejour")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BenskiReservationBundle:ReservationSejour')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find ReservationSejour entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing ReservationSejour entity.
     *
     * @Route("/{id}/edit", name="admin_reservation-sejour_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BenskiReservationBundle:ReservationSejour')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find ReservationSejour entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a ReservationSejour entity.
    *
    * @param ReservationSejour $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(ReservationSejour $entity)
    {
        $form = $this->createForm(new ReservationSejourType(), $entity, array(
            'action' => $this->generateUrl('admin_reservation-sejour_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing ReservationSejour entity.
     *
     * @Route("/{id}", name="admin_reservation-sejour_update")
     * @Method("PUT")
     * @Template("BenskiReservationBundle:ReservationSejour:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BenskiReservationBundle:ReservationSejour')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find ReservationSejour entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('admin_reservation-sejour_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a ReservationSejour entity.
     *
     * @Route("/{id}", name="admin_reservation-sejour_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('BenskiReservationBundle:ReservationSejour')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find ReservationSejour entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('admin_reservation-sejour'));
    }

    /**
     * Creates a form to delete a ReservationSejour entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_reservation-sejour_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/Benski/ReservationBundle/Resources/views/ReservationSejour/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>ReservationSejour edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_reservation-sejour') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Benski/ReservationBundle/Resources/views/ReservationSejour/layout.html.twig
{% extends "BenskiReservationBundle::layout.html.twig" %}

{% block title %}
Accueil - {{ parent() }}
{% endblock %}

{% block header %}
<h1>Reservation</h1>
{% endblock %}


{% block breadcrumb %}
{{ parent() }}
<li><a href="{{path('admin_reservation')}}">Reservation</a> <span class="divider">/</span></li>

{% endblock %}

{% block bundle_body %}
Attention, ce bloc est a définir

{% endblock %}

{% block left_menu %}
{% endblock %}

src/Benski/ReservationBundle/Resources/views/ReservationSejour/new.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>ReservationSejour creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_reservation-sejour') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/Benski/ReservationBundle/Resources/views/ReservationSejour/show.html.twig
{% extends 'BenskiReservationBundle:ReservationSejour:layout.html.twig' %}

{% block body -%}
<h1>ReservationSejour</h1>


<ul class="nav nav-tabs">
    <li class="active"><a href="#home" data-toggle="tab">Général</a></li>
  <li><a href="#profile" data-toggle="tab">Résumé</a></li>
  <li><a href="#messages" data-toggle="tab">Total</a></li>
  <li><a href="#settings" data-toggle="tab">Options</a></li>
</ul>


<div class="tab-content">
    <div class="tab-pane active" id="home">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ entity.id }}</td>
                </tr>
                <tr>
                    <th>Responsable</th>
                    <td>{{ entity.responsable }}</td>
                </tr>
                <tr>
                    <th>Total</th>
                    <td>{{ macro.int2prix(entity.total) }}</td>
                </tr>
                <tr>
                    <th>Statut</th>
                    <td>{{ entity.statut }}</td>
                </tr>
                <tr>
                    <th>Datecreation</th>
                    <td>{{ entity.dateCreation|date('Y-m-d H:i:s') }}</td>
                </tr>
                <tr>
                    <th>Datemodification</th>
                    <td>{{ entity.dateModification|date('Y-m-d H:i:s') }}</td>
                </tr>
                <tr>
                    <th>Reductions</th>
                    <td>{#{ entity.reductions }#}</td>
                </tr>
                <tr>
                    <th>Paiements</th>
                    <td>{#{ entity.paiements }#}</td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- NEW TAB PANE ------------------------------ -->
    <div class="tab-pane" id="profile">
        <table class="table table-bordered table-responsive" style="margin-top: 20px">

            <tbody>
                <tr>
                    <th>Destination</th>
                    <th>Date</th>
                    <th>Appartement</th>
                    <th>Participants</th>
                    <th>Pack</th>
                    <th>Total</th>
                </tr>
            {% set reservationSejour = entity %}
            {% set sejourReserve = reservationSejour.sejourReserve  %}
            {% set destination = sejourReserve.destination  %}
            {% set sejour = sejourReserve.sejour %}
            {% for appartementReserve in sejourReserve.appartementsReserves %}
            {% set appartement = appartementReserve.appartement %}
            {% set count = (sejourReserve.appartementsReserves|length) %}

                <tr>

                    {% if loop.first %}
                    <td rowspan="{{ count }}">{{ destination }}
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : destination })) %}
                        </div>
                    </td>
                    <td rowspan="{{ count }}">Du {{ sejour.dateDebut|date("d/m/Y") }}<br>
                        Au {{ sejour.dateFin|date("d/m/Y") }}
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : sejour })) %}
                        </div>
                    </td>
                    {% endif %}

                    <td>{{ appartement.nom }}
                    {{ macro.print_stars_bs2(appartement.qualite) }}
                        (<a href="#" class="prixParPersonne" >{{ macro.int2prix(appartementReserve.prix) }}€</a>)
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : appartement })) %}
                        </div>
                    </td>
                    <td>{{ appartementReserve.nombrePersonnes }}</td>
                    <td>{{ appartementReserve.packReserve.pack.nom }}
                    {{ macro.print_stars_bs2(appartementReserve.packReserve.pack.qualite) }}

                        (<a href="#" class="prixParPersonne" >{{ macro.int2prix(appartementReserve.packReserve.pack.prix) }}€</a>)
                        <div class="pull-right">     
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : appartementReserve.packReserve.pack })) %}
                        </div>
                    </td>
                    {% if loop.first %}
                    <td rowspan="{{ count }}">{{ macro.int2prix(sejourReserve.getTotal) }} €</td>
                    {% endif %}
                </tr>
                    {% endfor %}


            </tbody>
        </table>
        {% include "BenskiReservationBundle:ReservationSejour:element/appartements.html.twig" %}
    </div>
    <!-- NEW TAB PANE ------------------------------ -->
    <div class="tab-pane" id="messages">
        {% set sejourReserve = entity.sejourReserve %}
        <table class="table table-bordered table-responsive">

            <tbody>
                {% for ar in sejourReserve.appartementsReserves %}
                <tr>
                    <th>{{ar.appartement.nom }}
                        <small>
                    {% for i in 1..(ar.appartement.qualite) %}
                            <span class="glyphicon glyphicon-star"></span>
                    {% endfor %}
                        </small></th>
                    <th>Logement</th>
                    <th>Option</th>
                    <th>Total</th>
                </tr> 
                {% for participant in ar.participants %}
                <tr>
                    <td>{{participant.personne.firstName}} {{participant.personne.lastName}}</td>
                    <td>{{macro.int2prix(ar.prix)}} €</td>
                    <td>{{macro.int2prix(participant.getTotalOptions)}} €</td>
                    <td>{{macro.int2prix(participant.getTotal)}} €</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="3">Options de groupe</td>
                    <td><strong>{{macro.int2prix(ar.getTotalOptions())}} €</strong></td>
                </tr>
                <tr>
                    <td colspan="2">Prix du pack </td>
                    <td>{{ar.nombrePersonnes}} x
 {{macro.int2prix(ar.packReserve.prix)}} €</td>
                    <td><strong> {{macro.int2prix(ar.packReserve.getTotal)}} €</strong></td>
                </tr>
                <tr>
                    <td colspan="3">Sous total</td>
                    <td><strong>{{macro.int2prix(ar.getTotal())}} €</strong></td>
                </tr>
                {% endfor %}

                <tr class="active">
                    <th colspan="3">Total de votre séjour</th>
                    <td><strong>{{macro.int2prix(entity.getTotal())}} €</strong></td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- NEW TAB PANE ------------------------------ -->
    <div class="tab-pane" id="settings">

        {% include "BenskiReservationBundle:ReservationSejour:element/options.html.twig" %}
        
    </div>
</div>







<ul class="record_actions">
    <li>
        <a href="{{ path('admin_reservation-sejour') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('admin_reservation-sejour_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

  {% block javascripts %}
{{ parent() }}


</script>


  {% endblock %}

src/Benski/ReservationBundle/Resources/views/ReservationSejour/show.html_1.twig
{% extends 'BenskiReservationBundle:ReservationSejour:layout.html.twig' %}

{% block body -%}
<h1>ReservationSejour</h1>


<ul class="nav nav-tabs">
    <li class="active"><a href="#home" data-toggle="tab">Général</a></li>
  <li><a href="#profile" data-toggle="tab">Résumé</a></li>
  <li><a href="#messages" data-toggle="tab">Total</a></li>
  <li><a href="#settings" data-toggle="tab">Options</a></li>
</ul>


<div class="tab-content">
    <div class="tab-pane active" id="home">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ entity.id }}</td>
                </tr>
                <tr>
                    <th>Responsable</th>
                    <td>{{ entity.responsable }}</td>
                </tr>
                <tr>
                    <th>Total</th>
                    <td>{{ macro.int2prix(entity.total) }}</td>
                </tr>
                <tr>
                    <th>Statut</th>
                    <td>{{ entity.statut }}</td>
                </tr>
                <tr>
                    <th>Datecreation</th>
                    <td>{{ entity.dateCreation|date('Y-m-d H:i:s') }}</td>
                </tr>
                <tr>
                    <th>Datemodification</th>
                    <td>{{ entity.dateModification|date('Y-m-d H:i:s') }}</td>
                </tr>
                <tr>
                    <th>Reductions</th>
                    <td>{{ entity.reductions }}</td>
                </tr>
                <tr>
                    <th>Paiements</th>
                    <td>{{ entity.paiements }}</td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- NEW TAB PANE ------------------------------ -->
    <div class="tab-pane" id="profile">
        <table class="table table-bordered table-responsive" style="margin-top: 20px">

            <tbody>
                <tr>
                    <th>Destination</th>
                    <th>Date</th>
                    <th>Appartement</th>
                    <th>Participants</th>
                    <th>Pack</th>
                    <th>Total</th>
                </tr>
            {% set reservationSejour = entity %}
            {% set sejourReserve = reservationSejour.sejourReserve  %}
            {% set destination = sejourReserve.destination  %}
            {% set sejour = sejourReserve.sejour %}
            {% for appartementReserve in sejourReserve.appartementsReserves %}
            {% set appartement = appartementReserve.appartement %}
            {% set count = (sejourReserve.appartementsReserves|length) %}

                <tr>

                    {% if loop.first %}
                    <td rowspan="{{ count }}">{{ destination }}
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : destination })) %}
                        </div>
                    </td>
                    <td rowspan="{{ count }}">Du {{ sejour.dateDebut|date("d/m/Y") }}<br>
                        Au {{ sejour.dateFin|date("d/m/Y") }}
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : sejour })) %}
                        </div>
                    </td>
                    {% endif %}

                    <td>{{ appartement.nom }}
                    {{ macro.print_stars_bs2(appartement.qualite) }}
                        (<a href="#" class="prixParPersonne" >{{ macro.int2prix(appartementReserve.prix) }}€</a>)
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : appartement })) %}
                        </div>
                    </td>
                    <td>{{ appartementReserve.nombrePersonnes }}</td>
                    <td>{{ appartementReserve.packReserve.pack.nom }}
                    {{ macro.print_stars_bs2(appartementReserve.packReserve.pack.qualite) }}

                        (<a href="#" class="prixParPersonne" >{{ macro.int2prix(appartementReserve.packReserve.pack.prix) }}€</a>)
                        <div class="pull-right">     
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : appartementReserve.packReserve.pack })) %}
                        </div>
                    </td>
                    {% if loop.first %}
                    <td rowspan="{{ count }}">{{ macro.int2prix(sejourReserve.getTotal) }} €</td>
                    {% endif %}
                </tr>
                    {% endfor %}


            </tbody>
        </table>
    </div>
    <!-- NEW TAB PANE ------------------------------ -->
    <div class="tab-pane" id="messages">
        {% set sejourReserve = entity.sejourReserve %}
        <table class="table table-bordered table-responsive">

            <tbody>
                {% for ar in sejourReserve.appartementsReserves %}
                <tr>
                    <th>{{ar.appartement.nom }}
                        <small>
                    {% for i in 1..(ar.appartement.qualite) %}
                            <span class="glyphicon glyphicon-star"></span>
                    {% endfor %}
                        </small></th>
                    <th>Logement</th>
                    <th>Option</th>
                    <th>Total</th>
                </tr> 
                {% for participant in ar.participants %}
                <tr>
                    <td>{{participant.personne.firstName}} {{participant.personne.lastName}}</td>
                    <td>{{macro.int2prix(ar.prix)}} €</td>
                    <td>{{macro.int2prix(participant.getTotalOptions)}} €</td>
                    <td>{{macro.int2prix(participant.getTotal)}} €</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="3">Options de groupe</td>
                    <td><strong>{{macro.int2prix(ar.getTotalOptions())}} €</strong></td>
                </tr>
                <tr>
                    <td colspan="2">Prix du pack </td>
                    <td>{{ar.nombrePersonnes}} x
 {{macro.int2prix(ar.packReserve.prix)}} €</td>
                    <td><strong> {{macro.int2prix(ar.packReserve.getTotal)}} €</strong></td>
                </tr>
                <tr>
                    <td colspan="3">Sous total</td>
                    <td><strong>{{macro.int2prix(ar.getTotal())}} €</strong></td>
                </tr>
                {% endfor %}

                <tr class="active">
                    <th colspan="3">Total de votre séjour</th>
                    <td><strong>{{macro.int2prix(entity.getTotal())}} €</strong></td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- NEW TAB PANE ------------------------------ -->
    <div class="tab-pane" id="settings">
{% set sejourReserve = entity.sejourReserve %}
            {% for ar in sejourReserve.appartementsReserves %}
        <h2>{{ar.appartement.nom }}
            <small>
                    {% for i in 1..(ar.appartement.qualite) %}
                <span class="glyphicon glyphicon-star"></span>
                    {% endfor %} - {{ ar.nombrePersonnes}} personne(s) - 
                <a href="#" class="prixParPersonne" >{{ (ar.getPrix()/100)|number_format() }} €</a>
            </small>
            <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : ar.appartement })) %}
            </div>
        </h2>
        <hr>
        <ul>
                    {% for option in ar.optionsReserves %}
                    {% if option.isSelected %}
            <li>{{ option.getIntitule }} ({{ macro.int2prix(option.prix) }}€)</li>
                    {% endif %}
                    {% endfor %}
        </ul>
            {% for participant in ar.participants %}
            {% set id = ar.numero~"-"~participant.numero%}
        <h3>Participant n°{{ participant.numero }}</h3>
        <div class="row">
            <div class="span8">
                <dl class="dl-horizontal">
                    <dt>Nom</dt>
                    <dd>{{ participant.personne.firstName }} {{ participant.personne.lastName }}</dd>
                    <dt>Email</dt>
                    <dd>{{ participant.personne.email }}</dd>
                      {% if (participant.personne.address.isEmpty == true) %}
                    <dt>Adresse</dt>
                    <dd>
{{participant.personne.address.number}} {{participant.personne.address.street}}
                        <br>
                    {{participant.personne.address.city}}, {{participant.personne.address.zipCode}}<br>
                    {{participant.personne.address.country}}
                </dl>
                {% endif %}


            </div>
            <div class="col-sm-4">
                <h4>Options</h4>
                <ul>
                    {% for option in participant.optionsReserves %}
                    {% if option.isSelected %}
                    <li>{{ option.getIntitule }} ({{ macro.int2prix(option.prix) }}€)
                        <div class="pull-right">
                    {% render(controller("BenskiContentBundle:Link:displayButton", { 'object' : option.option })) %}
                        </div>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>

            {% endfor %}
            {% endfor %}
    </div>
</div>







<ul class="record_actions">
    <li>
        <a href="{{ path('admin_reservation-sejour') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('admin_reservation-sejour_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

  {% block javascripts %}
{{ parent() }}


</script>


  {% endblock %}